Student={"Name":"SHARON JENNY","Rollno":11,"Age":17,"Grade":"A"}
Student1=Student.fromkeys("sai","varun")
print(Student1)
Student.copy()
print(Student)
S2=Student.get("teju","rettu")
print(S2)
S3=Student.items()
print(S3)
S4=Student.keys()
print(S4)
S5=Student.popitem()
print(S5)
S6=Student.setdefault("chinnu")
print(S6)